import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// * Next.js가 우리한테 강제로 요구하는 것 중의 하나.
// * Framework -> 개발자한테 자기들의 규칙을 무조건 따르도록 요구.
// * 그 중의 하나 => 파일명은 우리가 정한대로 따라야 해. => layout.tsx(page.tsx의 레이아웃 배치), page.tsx(실제 웹 URL 페이지), error.tsx(500), not-found.tsx(404)
// * 공통 UI / Meta 로직은 layout.tsx에 작성한다 => 그러면 하위 모든 페이지에 적용된다.

// * layout 파일도 각 폴더마다 각자 가질 수 있는데 => 중복되면 계속 누적됩니다.
// ? ex) /student/profile 페이지에만 독특한 레이아웃을 적용하고 싶다면 ? => /student/profile/layout.tsx을 새로 만들고 적용하면 => /student/profile/page.tsx에 결과가 나타난다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
